# -*- coding: utf-8 -*-
"""Data Engineer intern .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lrZ6ae_y5YFZTzWhPLOA_JiyPkW_M_zu
"""

import pandas as pd

print("Library imported successfully")

df=pd.read_csv('student_performance.csv')

print("Dataset Loaded Successfully!")

#To view first 5 rows

df.head()

#To view last 5 rows


df.tail()

print("Shape of dataset:",df.shape)#No of rows and coloumns

print("Number of Students(rows):",df.shape[0])

print("Number of coloumns:",df.shape[0])

# To view all the coloumn names

print("Columns in the dataset: ")

print(df.columns.tolist())

# To view the data types

print("Data Types :")

print(df.dtypes)

#Statistical Data

df.describe()

print("Missing values in each coloumn :")
print(df.isnull().sum())


print("\nTotal missing values :")
print(df.isnull().sum().sum())

#To view a Specific coloumn Name

print("Student names:")
print(df['name'])

#To view Unique Departments

print("Departments in the Dataset:")
print(df['department'].unique())


print("\n How many Students per Department:")
print(df['department'].value_counts())

cs_students=df[df['department'] == 'Computer Science']

print("Number of Computer Science Students :" ,len(cs_students))


print("Computer Science Stdents")

high_attendence=df[df['attendance_percentage']>90]

print("Students with attendance above 90% :",len(high_attendence))

print(high_attendence[['name','department','attendance_percentage']])

#To find the Top_Student

df['total_score']=df['math_score']+df['science_score']+df['english_score']+df['programming_score']

#Calculate avg score per department

dept_avg=df.groupby('department')['total_score'].mean().round(2)


print("Average Total Score by Department;")
print(dept_avg)

df_sorted=df.sort_values(by='total_score',ascending=False)

print("Top 10 Students by Total Score :")
print(df_sorted[['name', 'department','total_score','attendance_percentage']].head(10))

"""1.How many students are from the electronics dept
2.What is the avg attendance of female students
3.who is the student with the lowest programming score
4.How many students scored anove 80 in maths
5.what is the avg total_acore for students with attendance above 90%

MINI PROJECT :Student data Explorer

Objective:
Create a student perfomance explorer using python and pandas to analyse student data and
"""

#PRACTICE QUESTIONS


electronics_students = df[df['department'] == 'Electronics']
num_electronics_students = len(electronics_students)
print(f"1. Number of students from the Electronics department: {num_electronics_students}")


female_students = df[df['gender'] == 'Female']
avg_female_attendance = female_students['attendance_percentage'].mean()
print(f"2. Average attendance of female students: {avg_female_attendance.round(2)}%")


lowest_programming_score_student = df.loc[df['programming_score'].idxmin()]
print(f"3. Student with the lowest programming score: {lowest_programming_score_student['name']} (Score: {lowest_programming_score_student['programming_score']})")


students_above_80_maths = df[df['math_score'] > 80]
num_students_above_80_maths = len(students_above_80_maths)
print(f"4. Number of students who scored above 80 in Maths: {num_students_above_80_maths}")


students_high_attendance = df[df['attendance_percentage'] > 90]
avg_total_score_high_attendance = students_high_attendance['total_score'].mean()
print(f"5. Average total score for students with attendance above 90%: {avg_total_score_high_attendance.round(2)}")

print("STUDENT PERFORMANCE EXPLORER - DATA ANALYSIS")


# 2. Dataset Overview
print("\n--- Dataset Overview ---")
print(f"Total number of students: {df.shape[0]}")
print(f"Total number of columns: {df.shape[1]}")
print(f"Number of unique departments: {df['department'].nunique()}")

# 3. Department wise analysis
print("\n--- Department-wise Student Count ---")
print(df['department'].value_counts())

# 4. Score Analysis
print("\n--- Score Analysis ---")
print(f"Highest Math Score: {df['math_score'].max()}")
print(f"Lowest Math Score: {df['math_score'].min()}")
print(f"Average Math Score: {df['math_score'].mean().round(2)}")
print(f"Average Programming Score: {df['programming_score'].mean().round(2)}")
print(f"Average Attendance Percentage: {df['attendance_percentage'].mean().round(2)}%")

# 5. Gender wise Analysis
print("\n--- Gender-wise Average Total Score ---")
print(df.groupby('gender')['total_score'].mean().round(2))

# 6. Top performers
print("\n--- Top 5 Students by Total Score ---")
top_5_students = df.sort_values(by='total_score', ascending=False).head(5)
print(top_5_students[['name', 'department', 'total_score']])

# 7. Attendance Analysis
print("\n--- Attendance Analysis (Below 75%) ---")
low_attendance_students = df[df['attendance_percentage'] < 75]

print("Students with attendance below 75%:")
print(low_attendance_students[['name', 'department', 'attendance_percentage']])
print("All students have attendance above 75%." * low_attendance_students.empty)